### ISSUE TITLE
Test Client's Image Processing Workflows Independently from Filesystem

### ISSUE THREAD

**Issue by nickdelgrosso** [HelmholtzAI-Consultants-Munich/data-centric-platform#22]

**Comment by christinab12** [comment]
Hi @nickdelgrosso was this part of the coding club showcasing? Can I close this or is it a real issue? If we should address, could you please elaborate a little?

Thanks!

**Comment by nickdelgrosso** [comment]
Hi, this was a potential issue for if the group was bigger and we needed three teams that day instead of two; it would have us do the same ports and adapters refactoring on another aspect of the code, though now I see that this particular refactor would have only been useful on the server code, not the client. Yes, this can be closed!

**Comment by christinab12** [comment]
Great, thanks for clarifying!
