### ISSUE TITLE
Image name substring search 

### ISSUE THREAD

**Issue by christinab12** [HelmholtzAI-Consultants-Munich/data-centric-platform#31]
If we have 1.tiff and 11.tiff and generate labels and open 1.tiff, then masks of 1_seg.tiff and 11_seg.tiff both open

**Comment by hpelin** [comment]
This should be fixed now in this [commit](https://github.com/HelmholtzAI-Consultants-Munich/data-centric-platform/pull/30/commits/ffe5adfef9c1fcb3d469d07e440f5164c62967bc). Please close the issue once tested again.
